help petr navigate this mess
maiqueb/macvtap-cni pull request #1
Opened 2019-12-04 11:24 UTC by maiqueb

2019-12-05 16:01 UTC, phoracek requested changes

2019-12-05 16:01 UTC, phoracek commented on README.md
> +* `type`   (string, required): "ovs".
macvtap

2019-12-05 16:01 UTC, phoracek commented on README.md
> +    "mac": "02:03:04:05:06:07"
This should go through env variable, not through configuration. Remember, configuration is set in NetworkAttachmentDefinition and shared by all attachments.

2019-12-05 16:01 UTC, phoracek commented on macvtap.go
> +// Copyright 2015 CNI authors
Ancient!

2019-12-05 16:01 UTC, phoracek commented on macvtap.go
> +	defer func() {
Why is calling this at the end of the function useful? There is nothing that could fail after this point.

2019-12-05 16:01 UTC, phoracek commented on macvtap.go
> +	tmpName, err := ip.RandomVethName()
With this you will create a macvtap device with "veth" in its name. I would not want to debug that.

2019-12-05 16:01 UTC, phoracek commented on macvtap.go
> +		// TODO: duplicate following lines for ipv6 support, when it will be added in other places
As a random contributor, I would not understand what do you want from me here

2019-12-05 16:01 UTC, phoracek commented on macvtap.go
> +		ipv4SysctlValueName := fmt.Sprintf(IPv4InterfaceArpProxySysctlTemplate, tmpName)
I would mention that it is an arp config there

2019-12-05 16:01 UTC, phoracek commented on macvtap.go
> +			_ = netlink.LinkDel(mv)
You don't need to assign the return value if you don't use it

2019-12-05 16:01 UTC, phoracek commented on macvtap.go
> +			_ = netlink.LinkDel(mv)
ditto

2019-12-16 12:28 UTC, maiqueb commented on README.md
> +    "mac": "02:03:04:05:06:07"
Handled on https://github.com/maiqueb/macvtap-cni/pull/2

2019-12-17 15:03 UTC, maiqueb commented on README.md
> +* `type`   (string, required): "ovs".
Done.

2019-12-17 15:03 UTC, maiqueb commented on macvtap.go
> +// Copyright 2015 CNI authors
Done

2019-12-17 15:03 UTC, maiqueb commented on macvtap.go
> +	defer func() {
Done in https://github.com/maiqueb/macvtap-cni/pull/3

2019-12-20 14:03 UTC, maiqueb commented on macvtap.go
> +	tmpName, err := ip.RandomVethName()
It's name if moved back to the original in https://github.com/maiqueb/macvtap-cni/pull/1/files#diff-be3d8974c719c4ceced4dedbc3ef5fa7R171 .

2019-12-20 14:04 UTC, closed without merging